# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/prince/share/wifibroadcast

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/prince/share/wifibroadcast

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/prince/share/wifibroadcast/CMakeFiles /home/prince/share/wifibroadcast/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/prince/share/wifibroadcast/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tx

# Build rule for target.
tx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tx
.PHONY : tx

# fast build rule for target.
tx/fast:
	$(MAKE) -f CMakeFiles/tx.dir/build.make CMakeFiles/tx.dir/build
.PHONY : tx/fast

#=============================================================================
# Target rules for targets named camera

# Build rule for target.
camera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 camera
.PHONY : camera

# fast build rule for target.
camera/fast:
	$(MAKE) -f H264_camera/CMakeFiles/camera.dir/build.make H264_camera/CMakeFiles/camera.dir/build
.PHONY : camera/fast

fec.o: fec.c.o

.PHONY : fec.o

# target to build an object file
fec.c.o:
	$(MAKE) -f CMakeFiles/tx.dir/build.make CMakeFiles/tx.dir/fec.c.o
.PHONY : fec.c.o

fec.i: fec.c.i

.PHONY : fec.i

# target to preprocess a source file
fec.c.i:
	$(MAKE) -f CMakeFiles/tx.dir/build.make CMakeFiles/tx.dir/fec.c.i
.PHONY : fec.c.i

fec.s: fec.c.s

.PHONY : fec.s

# target to generate assembly for a file
fec.c.s:
	$(MAKE) -f CMakeFiles/tx.dir/build.make CMakeFiles/tx.dir/fec.c.s
.PHONY : fec.c.s

tx.o: tx.cpp.o

.PHONY : tx.o

# target to build an object file
tx.cpp.o:
	$(MAKE) -f CMakeFiles/tx.dir/build.make CMakeFiles/tx.dir/tx.cpp.o
.PHONY : tx.cpp.o

tx.i: tx.cpp.i

.PHONY : tx.i

# target to preprocess a source file
tx.cpp.i:
	$(MAKE) -f CMakeFiles/tx.dir/build.make CMakeFiles/tx.dir/tx.cpp.i
.PHONY : tx.cpp.i

tx.s: tx.cpp.s

.PHONY : tx.s

# target to generate assembly for a file
tx.cpp.s:
	$(MAKE) -f CMakeFiles/tx.dir/build.make CMakeFiles/tx.dir/tx.cpp.s
.PHONY : tx.cpp.s

wifibroadcast.o: wifibroadcast.cpp.o

.PHONY : wifibroadcast.o

# target to build an object file
wifibroadcast.cpp.o:
	$(MAKE) -f CMakeFiles/tx.dir/build.make CMakeFiles/tx.dir/wifibroadcast.cpp.o
.PHONY : wifibroadcast.cpp.o

wifibroadcast.i: wifibroadcast.cpp.i

.PHONY : wifibroadcast.i

# target to preprocess a source file
wifibroadcast.cpp.i:
	$(MAKE) -f CMakeFiles/tx.dir/build.make CMakeFiles/tx.dir/wifibroadcast.cpp.i
.PHONY : wifibroadcast.cpp.i

wifibroadcast.s: wifibroadcast.cpp.s

.PHONY : wifibroadcast.s

# target to generate assembly for a file
wifibroadcast.cpp.s:
	$(MAKE) -f CMakeFiles/tx.dir/build.make CMakeFiles/tx.dir/wifibroadcast.cpp.s
.PHONY : wifibroadcast.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tx"
	@echo "... camera"
	@echo "... fec.o"
	@echo "... fec.i"
	@echo "... fec.s"
	@echo "... tx.o"
	@echo "... tx.i"
	@echo "... tx.s"
	@echo "... wifibroadcast.o"
	@echo "... wifibroadcast.i"
	@echo "... wifibroadcast.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

